name: default-app

labels:
  enabled: true


#Credential to access Private Registry
imagePullSecrets: []
#Name overrride will be RELEASE-NAME-$nameOverride
nameOverride: ""
#Full name overrride will be $fullnameOverride
fullnameOverride: ""

replicaCount: 1

deployment:
  annotations:
    enabled: false
    data:

image:
  repository: lusoal/test-helm
  imageTag: latest
  pullPolicy: IfNotPresent

container:
  port: 5000
  healthcheck:
    enabled: true
    livenessProbe: /health
    readinessProbe: /health

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: NodePort
  port: 80
  annotations:
    enabled: false
    data:

secretEnvs:
  enabled: false
  data: #Your application secrets
    - name: "MY_SECRET_NAME"
  
configMap:
  enabled: true
  data: #Your application environment variables
    DatabaseUrl: postgresql://xxxxx:5432/xxxx
    
serviceAccount:
  create: true

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  enabled: false
  data:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000



ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


nodeSelector: {}

tolerations: []

affinity: {}
