{{- $chartName :=  include "default-app.fullname" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "default-app.fullname" . }}
  labels:
    {{- include "default-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "default-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "default-app.selectorLabels" . | nindent 8 }}
    {{- if .Values.deployment.annotations.enabled}}
    annotations:
      {{- toYaml .Values.deployment.annotations.data | nindent 8 }}
    {{- end}}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "default-app.serviceAccountName" . }}
      containers:
        - name: {{ template "default-app.fullname" . }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            {{- toYaml .Values.securityContext.data | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          {{- if .Values.container.livenessProbe }}
          livenessProbe:
            httpGet:
              path: "{{ .Values.container.livenessProbe }}"
              port: http
          {{- end }}
          {{- if .Values.container.readinessProbe }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.container.livenessProbe }}"
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.configMap.enabled }}
          envFrom:
           - configMapRef:
              name: {{ template "default-app.fullname" . }}
          {{- end }}
          {{- if .Values.secretEnvs.enabled }}
          env:
            {{- range .Values.secretEnvs.data }}
            - name: "{{ .name }}"
              valueFrom:
                secretKeyRef: 
                  name: {{ $chartName }}
                  key: "{{ .name }}"
            {{- end }}
          {{- end }}
      {{- if .Values.nodeSelector }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
    {{- if .Values.affinity }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- if .Values.tolerations }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}