apiVersion: v1
kind: Service
metadata:
  name: {{ template "default-app.fullname" . }}
  labels:
    {{- include "default-app.labels" . | nindent 4 }}
  {{- if .Values.service.annotations.enabled}}
  annotations:
    {{- toYaml .Values.service.annotations.data | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
  selector:
    {{- include "default-app.selectorLabels" . | nindent 4 }}
