{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "default-app.fullname" . }}
  labels:
{{ include "default-app.labels" . | nindent 4 }}
{{- end -}}
